# The URL the site will be built for
base_url = "https://gridbeam.xyz"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here

[extra.footer]
links = [
    { url = "about", label = "About" },
    { url = "sitemap.xml", label = "Sitemap" },
]
notice = '<a href="https://github.com/villagekit/gridbeam.xyz">gridbeam.xyz</a> made with ❤️ by <a href="https://mikey.nz">Mikey</a> (<a href="https://villagekit.com">Village Kit</a>)'

[extra.navbar]
links = [
    { url = "stories", label = "Stories" },
    { url = "tags", label = "Tags" },
    { url = "movies", label = "Movies" },
]

[extra.social]
codeberg = ""
github = "https://github.com/villagekit/gridbeam.xyz"
gitlab = ""
stackoverflow = ""
mastodon = ""
linkedin = ""
instagram = ""
youtube = ""
signal = ""
telegram = ""
email = ""
phone = ""

[extra.favicon]
svg = "favicon.svg"
