packages:
  - "ui"
  - "gridkit"
  - "gridkit/apps/*"
  - "gridkit/commands/*"
  - "gridkit/core/*"
  - "gridkit/dev/*"
  - "gridkit/kit-plugins/*"
  - "gridkit/parts/*"
  - "gridkit/products/*"
  - "gridkit/util/*"
