export { default as flexible } from './flexible.svg'
export { default as icon } from './icon.svg'
export { default as recycle } from './recycle.svg'
export { default as life } from './life.svg'
export { default as share } from './share.svg'
export { default as playground } from './playground.svg'
export { default as tree } from './tree.svg'
export { default as gridBeam } from './grid-beam.gif'
export { default as gridBeamKit } from './grid-beam-kit.gif'

// examples
export { default as gridBeamDesk0 } from './grid-beam-desk-0.gif'
export { default as gridBeamDesk1 } from './grid-beam-desk-1.gif'
export { default as gridBeamChair } from './grid-beam-chair.gif'
export { default as gridBeamDrawer } from './grid-beam-drawer.gif'
export { default as gridBeamCube } from './grid-beam-cube.gif'
