export { default as flexible } from './flexible.svg'
export { default as icon } from './icon.svg'
export { default as recycle } from './recycle.svg'
export { default as life } from './life.svg'
export { default as share } from './share.svg'
export { default as playground } from './playground.svg'
export { default as tree } from './tree.svg'
