#!/usr/bin/env node
// scripts/generate-designs-data.ts
//
// Reads every product under `./products/<id>/` and emits a single TypeScript
// module (`app/_lib/designs-data.generated.ts`) with the parsed TOML meta + the
// design's exported code, compiled from TypeScript to JavaScript, inlined.
//
// We do this because the runtime target (Cloudflare Workers via OpenNext) does
// not bundle arbitrary repo files alongside the worker — only JS that the
// worker imports gets included. Reading `./products/` with `node:fs` at request
// time blows up with `no such file or directory, readdir '/bundle/products'`.
// Generating a JS module that imports the data inline sidesteps that entirely.
//
// The compile block is ported from
// https://github.com/villagekit/node-modules/blob/fce357d/packages/designs/src/index.ts
// (inside legacy's `getDesign`): `@swc/wasm`'s `transform` with the same options, so the page
// receives JavaScript with an inline source map and an `exports` ending `.js`,
// and the engine's renderer never loads `@swc/wasm-web` in the browser to
// compile the TypeScript on each visit. It runs here and not in `getDesign`
// because that function renders on the Worker per request under OpenNext's
// default `dummy` incremental cache, where a Node binding that loads a 20 MB
// wasm file from disk cannot go; this script is the build step that already
// writes the module. The output is deterministic for the pinned `@swc/wasm`
// version, which the drift check (`just generated`) relies on.

import { existsSync } from 'node:fs'
import { readFile, readdir, writeFile } from 'node:fs/promises'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

import { transform } from '@swc/wasm'
import type { ProductMeta } from '@villagekit/product'
import { parse as parseToml } from 'smol-toml'

const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const DESIGNS_DIR = join(REPO_ROOT, 'products')
const OUT_PATH = join(REPO_ROOT, 'app', '_lib', 'designs-data.generated.ts')

async function main(): Promise<void> {
  if (!existsSync(DESIGNS_DIR)) {
    throw new Error(`Designs directory not found: ${DESIGNS_DIR}`)
  }

  const entries = await readdir(DESIGNS_DIR, { withFileTypes: true })
  const ids = entries
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .sort()

  const designs = await Promise.all(
    ids.map(async (id) => {
      const tomlPath = join(DESIGNS_DIR, id, 'villagekit.toml')
      const tomlContents = await readFile(tomlPath, 'utf8')
      const parsed = parseToml(tomlContents)
      const meta = parsed.product as ProductMeta
      const codePath = join(DESIGNS_DIR, id, meta.exports)
      let code = await readFile(codePath, 'utf8')

      // if TypeScript code, compile to JavaScript
      if (meta.exports.endsWith('.ts')) {
        meta.exports = `${meta.exports.substring(0, meta.exports.length - 3)}.js`
        code = (
          await transform(code, {
            filename: meta.exports,
            jsc: {
              parser: {
                syntax: 'typescript',
              },
            },
            module: {
              noInterop: true,
              strict: true,
              type: 'es6',
            },
            sourceMaps: 'inline',
          })
        ).code
      }

      return { id, meta, code }
    }),
  )

  const body = designs
    .map(({ id, meta, code }) => {
      return `  ${JSON.stringify(id)}: {\n    meta: ${JSON.stringify(meta, null, 4).replace(/\n/g, '\n    ')},\n    code: ${JSON.stringify(code)},\n  },`
    })
    .join('\n')

  const output = `// @generated by scripts/generate-designs-data.ts — DO NOT EDIT.
// Run \`pnpm generate:designs\` after changing files under \`./products/\`.

import type { ProductMeta } from '@villagekit/product'

export interface RawDesignEntry {
  meta: ProductMeta
  code: string
}

export const designsData: Record<string, RawDesignEntry> = {
${body}
}
`

  await writeFile(OUT_PATH, output, 'utf8')
  console.info(
    { designs: designs.length, path: OUT_PATH.replace(`${REPO_ROOT}/`, '') },
    'designs data written',
  )
}

main().catch((err: unknown) => {
  console.error(err)
  process.exit(1)
})
